name: Scrape selenium test

on:
  schedule:
    # 这个 cron 表示每天凌晨 2 点运行一次
    - cron: '0 4 * * *'
  workflow_dispatch:
    # 手动触发

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Scrape website
      run: |
        python scripts/scrape-selenium.py